### ISSUE TITLE
Permission to use code for rules_ocaml?

### ISSUE THREAD

**Issue by mobileink** [rgrinberg/deriving-slowly#1]
Hi,

Thanks for this and the blog post, very helpful.

I'm writing Bazel rules for OCaml (https://github.com/mobileink/obazl) and I would like to include this code in the examples section, to demonstrate how to build (not code) simple PPX stuff.  Of course I would place and acknowledgement and prominent messages directing readers to your blog post.

That ok with you?

Thanks,

Gregg

**Comment by rgrinberg** [comment]
You're free to use whatever you'd like from this repository.
